### PR TITLE
[WIP] - Completely rename of the project from keycloak-proxy to keycloak-gatekeeper

### PR DESCRIPTION
**Pull request by abstractj**
Pending tasks:

- [ ] Publish a Docker image. Actually the image is published on Quay. Not sure if we want to keep this.

- [ ] Publish GoDocs to https://godoc.org/github.com/keycloak/keycloak-gatekeeper instead of https://godoc.org/github.com/gambol99/keycloak-proxy

- [ ] Setup coveralls for this release

- [ ] Rephrase the whole README file

### CODE REVIEW

**Comment by jgoux** [comment]
Hello, what's the current state of the project with docker?

I looked for a docker image but the only one I could find is : https://hub.docker.com/r/jboss/keycloak-proxy/ which is deprecated.

Thanks for your help.

**Comment by styk-tv** [comment]
I just want to add for the record this is a very very cool idea. Long awaited official one.

**Comment by abstractj** [comment]
@jgoux @styk-tv we need to update the docs for the Gatekeeper release. But the docker image is available here https://hub.docker.com/r/keycloak/keycloak-gatekeeper/. If you have any questions, please to ask/provide feedback on keycloak-user mailing list.

**Comment by abstractj** [comment]
@jgoux https://www.keycloak.org/community.html

**Pull request merged**
